# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=64)),
                ('cti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIapp.Cti')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Severity', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('assigned_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Ti_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('photo', models.ImageField(default='static/upload_images/user-1.jpg', upload_to='static/upload_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIapp.Ti_user'),
        ),
        migrations.AddField(
            model_name='cti',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIapp.Ti_user'),
        ),
        migrations.AddField(
            model_name='cti',
            name='parent_Cti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIapp.Cti'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TIapp.Ti_user'),
        ),
    ]
